# Generated by Django 4.1 on 2022-09-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_like_post_alter_like_user_alter_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='date',
        ),
    ]
